//! TEAMS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING
//!
//! Reason this exists is because rust-analyer will expand the proc macro as you type the name of
//! the class, and that leads to a bunch of files that tend to break stuff like M.java, My.java,
//! MyI.java, etc. This clears all of them as the proc macro will regenerate them. Build scripts run
//! before proc macros as well (well, there's more nuance then that), so this won't immediately
//! remove the newly generated files either.

fn main() {
    // get all teamcode
    for entry in
        match std::fs::read_dir("../src/main/java/org/firstinspires/ftc/teamcode/autogenerated") {
            Ok(v) => v,
            Err(_) => return, // if that path doesn't exist, fail silently
        }
    {
        let entry = entry.unwrap();

        // if it isn't a file, skip it
        if !entry.file_type().unwrap().is_file() {
            continue;
        }

        // check if it is generated by us
        if std::fs::read_to_string(entry.path())
            .unwrap()
            .starts_with("/* DO NOT EDIT THIS FILE - it is machine generated by ftc-rust")
        {
            // it is, remove it, it'll be remade by the proc macro after this runs
            // (proc macros are expanded at compile time, build scripts run before
            // the crate is compiled)
            std::fs::remove_file(entry.path()).unwrap();
        }
    }
}
