/* DO NOT EDIT THIS FILE - it is machine generated by ftc-rust v12.0.0.
DO NOT PUT YOUR FILES IN THIS DIRECTORY, THEY MAY BE DELETED */

package org.firstinspires.ftc.teamcode.autogenerated;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import dev.frozenmilk.sinister.loading.Pinned;

@Autonomous(name = "Autonomous")

@Pinned
public class Auto extends LinearOpMode {
    private long rust_id;
    @Override
    public native void runOpMode();

    static {
        System.loadLibrary("team_code_rust");
    }
}
