/* DO NOT EDIT THIS FILE - it is machine generated by ftc-rust v11.2.0.
DO NOT PUT YOUR FILES IN THIS DIRECTORY, THEY MAY BE DELETED */

package org.firstinspires.ftc.teamcode.autogenerated;

import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;

@TeleOp(name = "Example: My Iterative Op Mode", group = "Example")

public class MyIterativeOpMode extends OpMode {
    private long rust_id;
    @Override
    public native void init();
    @Override
    public native void init_loop();
    @Override
    public native void start();
    @Override
    public native void loop();
    @Override
    public native void stop();

    static {
        System.loadLibrary("team_code_rust");
    }
}
